### ISSUE TITLE
ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 6, 32, 2), (None, 2, 32, 2), (None, 2, 32, 2)]

### ISSUE THREAD

**Issue by hafizali12** [lucktroy/DeepST#19]
compiling model...
**at the first time, it takes a few minites to compile if you use [Theano] as the backend**
Traceback (most recent call last):
  File "exptTaxiBJ.py", line 212, in <module>
    main()
  File "exptTaxiBJ.py", line 142, in main
    model = build_model(external_dim)
  File "exptTaxiBJ.py", line 69, in build_model
    external_dim=external_dim, nb_residual_unit=nb_residual_unit)
  File "C:\Users\ahmadali\Anaconda3\envs\py27\lib\site-packages\deepst-0.0.1-py2.7.egg\deepst\models\STResNet.py", line 87, in stresnet
    main_output = merge(new_outputs, mode='sum')
  File "C:\Users\ahmadali\Anaconda3\envs\py27\lib\site-packages\keras\engine\topology.py", line 1674, in merge
    name=name)
  File "C:\Users\ahmadali\Anaconda3\envs\py27\lib\site-packages\keras\engine\topology.py", line 1293, in __init__
    node_indices, tensor_indices)
  File "C:\Users\ahmadali\Anaconda3\envs\py27\lib\site-packages\keras\engine\topology.py", line 1329, in _arguments_validation
    'Layer shapes: %s' % input_shapes)
ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 6, 32, 2), (None, 2, 32, 2), (None, 2, 32, 2)]
Please can anyone help me to solve this problem. 
I used keras 2.0.2
configuration file of Keras: ~/.keras/keras.json

```

{

"image_data_format": "channels_first",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "theano"
}


but still face the problem

**Comment by JasonPin** [comment]
```
len_period = 1  # length of peroid dependent sequence
len_trend = 1 # length of trend dependent sequence
```
change 1 to 3, it is just a mistake.

**Comment by zhuqiangbiubiubiu** [comment]
Conv2D(filters=filters, kernel_size=(nb_row,nb_col), data_format='channels_first',subsample=subsample, padding="same")(activation)

**Comment by KingWang93** [comment]
I also encountered the same problem,but I'm using python3.6 and keras2.2.4. some API in python has changed.
the function merge() in old keras version can not work in keras 2.2.4. So I changed it to the function add().

but I got the error:

F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py:71: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_size=(3, 3), filters=64, padding="same")`
  nb_filter=64, nb_row=3, nb_col=3, border_mode="same")(input)
F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py:30: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_size=(3, 3), filters=64, strides=(1, 1), padding="same")`
  return Convolution2D(nb_filter=nb_filter, nb_row=nb_row, nb_col=nb_col, subsample=subsample, border_mode="same")(activation)
F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py:78: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_size=(3, 3), filters=2, padding="same")`
  nb_filter=nb_flow, nb_row=3, nb_col=3, border_mode="same")(activation)
Traceback (most recent call last):
  File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/KingWang/个人项目/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ.py", line 212, in <module>
    main()
  File "F:/KingWang/个人项目/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ.py", line 142, in main
    model = build_model(external_dim)
  File "F:/KingWang/个人项目/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ.py", line 69, in build_model
    external_dim=external_dim, nb_residual_unit=nb_residual_unit)
  File "F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py", line 89, in stresnet
    main_output = add(new_outputs)
  File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\merge.py", line 555, in add
    return Add(**kwargs)(inputs)
  File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\merge.py", line 91, in build
    shape)
  File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\merge.py", line 61, in _compute_elemwise_op_output_shape
    str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (6, 32, 2) (2, 32, 2)

**Comment by KingWang93** [comment]
> I also encountered the same problem,but I'm using python3.6 and keras2.2.4. some API in python has changed.
> the function merge() in old keras version can not work in keras 2.2.4. So I changed it to the function add().
> 
> but I got the error:
> 
> F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py:71: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_size=(3, 3), filters=64, padding="same")`
> nb_filter=64, nb_row=3, nb_col=3, border_mode="same")(input)
> F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py:30: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_size=(3, 3), filters=64, strides=(1, 1), padding="same")`
> return Convolution2D(nb_filter=nb_filter, nb_row=nb_row, nb_col=nb_col, subsample=subsample, border_mode="same")(activation)
> F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py:78: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_size=(3, 3), filters=2, padding="same")`
> nb_filter=nb_flow, nb_row=3, nb_col=3, border_mode="same")(activation)
> Traceback (most recent call last):
> File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1664, in 
> main()
> File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
> globals = debugger.run(setup['file'], None, None, is_module)
> File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
> pydev_imports.execfile(file, globals, locals) # execute the script
> File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "F:/KingWang/个人项目/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ.py", line 212, in 
> main()
> File "F:/KingWang/个人项目/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ.py", line 142, in main
> model = build_model(external_dim)
> File "F:/KingWang/个人项目/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ.py", line 69, in build_model
> external_dim=external_dim, nb_residual_unit=nb_residual_unit)
> File "F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py", line 89, in stresnet
> main_output = add(new_outputs)
> File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\merge.py", line 555, in add
> return Add(**kwargs)(inputs)
> File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\base_layer.py", line 431, in **call**
> self.build(unpack_singleton(input_shapes))
> File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\merge.py", line 91, in build
> shape)
> File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\merge.py", line 61, in _compute_elemwise_op_output_shape
> str(shape1) + ' ' + str(shape2))
> ValueError: Operands could not be broadcast together with shapes (6, 32, 2) (2, 32, 2)

https://github.com/lucktroy/DeepST/blob/master/keras_configuration.md

**Comment by zhuqiangbiubiubiu** [comment]
This is independent of the functions,add() and merge() both need inputs have same shape,your inputs' shape is  inconsistent ,check Conv2D() and make sure it has same input and output 


| |
朱强
|
|
zhuqiangxs@163.com
|
签名由网易邮箱大师定制
On 11/20/2018 22:56，KingWang93<notifications@github.com> wrote：

I also encountered the same problem,but I'm using python3.6 and keras2.2.4. some API in python has changed.
the function merge() in old keras version can not work in keras 2.2.4. So I changed it to the function add().

but I got the error:

F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py:71: UserWarning: Update your Conv2D call to the Keras 2 API: Conv2D(kernel_size=(3, 3), filters=64, padding="same")
nb_filter=64, nb_row=3, nb_col=3, border_mode="same")(input)
F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py:30: UserWarning: Update your Conv2D call to the Keras 2 API: Conv2D(kernel_size=(3, 3), filters=64, strides=(1, 1), padding="same")
return Convolution2D(nb_filter=nb_filter, nb_row=nb_row, nb_col=nb_col, subsample=subsample, border_mode="same")(activation)
F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py:78: UserWarning: Update your Conv2D call to the Keras 2 API: Conv2D(kernel_size=(3, 3), filters=2, padding="same")
nb_filter=nb_flow, nb_row=3, nb_col=3, border_mode="same")(activation)
Traceback (most recent call last):
File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1664, in
main()
File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
globals = debugger.run(setup['file'], None, None, is_module)
File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File "D:\Program Files (x86)\PyCharm 2018.2.4\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "F:/KingWang/个人项目/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ.py", line 212, in
main()
File "F:/KingWang/个人项目/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ.py", line 142, in main
model = build_model(external_dim)
File "F:/KingWang/个人项目/DeepST/scripts/papers/AAAI17/TaxiBJ/exptTaxiBJ.py", line 69, in build_model
external_dim=external_dim, nb_residual_unit=nb_residual_unit)
File "F:\KingWang\个人项目\DeepST\deepst\models\STResNet.py", line 89, in stresnet
main_output = add(new_outputs)
File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\merge.py", line 555, in add
return Add(**kwargs)(inputs)
File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\base_layer.py", line 431, in call
self.build(unpack_singleton(input_shapes))
File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\merge.py", line 91, in build
shape)
File "C:\Users\KingWang\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\merge.py", line 61, in _compute_elemwise_op_output_shape
str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (6, 32, 2) (2, 32, 2)

https://github.com/lucktroy/DeepST/blob/master/keras_configuration.md

**Comment by zhuqiangbiubiubiu** [comment]
add  data_format='channels_first' to Conv2D

**Comment by KingWang93** [comment]
> add data_format='channels_first' to Conv2D

do you know where to download the meteorology data?

**Comment by alexofficial** [comment]
> ```
> len_period = 1  # length of peroid dependent sequence
> len_trend = 1 # length of trend dependent sequence
> ```
> 
> change 1 to 3, it is just a mistake.

This refers to exptTexiBJ.py. But what about the exptBikeNYC.py? Are correct len_period and len_tred equals to 4?

**Comment by zhuqiangbiubiubiu** [comment]
The value of len_period and len _trend can be set freely.The author is set to one means that use periods (t-1*7*48,t-1*48,t-1)to predict t.Every time period has two 32x32 matrixs.So the shape of X-train is (,6,32,32),y-train is(,2,32,32)The reason for the value error is that conv2d defaults to channellast, ie channels=32, in fact channels should be equal to 6, so modify to channelfirst.


发自我的 iPhone
